import type { PlantType } from "./types";

export const PLANT_TYPES: PlantType[] = [
  {
    id: "monstera-deliciosa",
    latinName: "Monstera deliciosa",
    turkishNames: ["Devetabanı"],
    englishNames: ["Monstera", "Swiss Cheese Plant"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "ficus-elastica",
    latinName: "Ficus elastica",
    turkishNames: ["Kauçuk"],
    englishNames: ["Rubber Plant"],
    defaultWateringDays: 8,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 365,
  },
  {
    id: "spathiphyllum",
    latinName: "Spathiphyllum wallisii",
    turkishNames: ["Barış Çiçeği"],
    englishNames: ["Peace Lily"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 300,
  },
  {
    id: "epipremnum-aureum",
    latinName: "Epipremnum aureum",
    turkishNames: ["Salon Sarmaşığı", "Pothos"],
    englishNames: ["Pothos", "Devil's Ivy"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "sansevieria-trifasciata",
    latinName: "Dracaena trifasciata",
    turkishNames: ["Paşa Kılıcı"],
    englishNames: ["Snake Plant"],
    defaultWateringDays: 14,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 420,
  },
  {
    id: "aloe-vera",
    latinName: "Aloe vera",
    turkishNames: ["Aloe Vera", "Sarısabır"],
    englishNames: ["Aloe Vera"],
    defaultWateringDays: 14,
    defaultFeedingDays: 50,
    defaultSoilChangeDays: 420,
  },
  {
    id: "crassula-ovata",
    latinName: "Crassula ovata",
    turkishNames: ["Para Ağacı"],
    englishNames: ["Jade Plant", "Money Tree"],
    defaultWateringDays: 12,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 365,
  },
  {
    id: "zamioculcas-zamiifolia",
    latinName: "Zamioculcas zamiifolia",
    turkishNames: ["ZZ Bitkisi", "Zamya"],
    englishNames: ["ZZ Plant"],
    defaultWateringDays: 14,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 420,
  },
  {
    id: "dracaena-marginata",
    latinName: "Dracaena marginata",
    turkishNames: ["Drasena"],
    englishNames: ["Dragon Tree", "Madagascar Dragon Tree"],
    defaultWateringDays: 8,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 365,
  },
  {
    id: "chlorophytum-comosum",
    latinName: "Chlorophytum comosum",
    turkishNames: ["Kurdele Çiçeği"],
    englishNames: ["Spider Plant"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "anthurium-andraeanum",
    latinName: "Anthurium andraeanum",
    turkishNames: ["Antoryum", "Flamingo Çiçeği"],
    englishNames: ["Anthurium", "Flamingo Flower"],
    defaultWateringDays: 6,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 365,
  },
  {
    id: "phalaenopsis",
    latinName: "Phalaenopsis",
    turkishNames: ["Orkide"],
    englishNames: ["Orchid", "Moth Orchid"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 540,
  },
  {
    id: "saintpaulia",
    latinName: "Saintpaulia ionantha",
    turkishNames: ["Afrika Menekşesi", "Menekşe"],
    englishNames: ["African Violet"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 300,
  },
  {
    id: "hedera-helix",
    latinName: "Hedera helix",
    turkishNames: ["Orman Sarmaşığı"],
    englishNames: ["English Ivy"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "yucca-elephantipes",
    latinName: "Yucca elephantipes",
    turkishNames: ["Yuka"],
    englishNames: ["Yucca", "Spineless Yucca"],
    defaultWateringDays: 12,
    defaultFeedingDays: 40,
    defaultSoilChangeDays: 420,
  },
  {
    id: "ficus-benjamina",
    latinName: "Ficus benjamina",
    turkishNames: ["Benjamin"],
    englishNames: ["Weeping Fig"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "ficus-lyrata",
    latinName: "Ficus lyrata",
    turkishNames: ["Keman Yapraklı Kauçuk", "Pandora"],
    englishNames: ["Fiddle Leaf Fig"],
    defaultWateringDays: 8,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "calathea",
    latinName: "Calathea",
    turkishNames: ["Kalatya", "Dua Çiçeği"],
    englishNames: ["Calathea", "Prayer Plant"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 300,
  },
  {
    id: "maranta-leuconeura",
    latinName: "Maranta leuconeura",
    turkishNames: ["Dua Bitkisi"],
    englishNames: ["Prayer Plant"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 300,
  },
  {
    id: "philodendron-scandens",
    latinName: "Philodendron scandens",
    turkishNames: ["Filodendron"],
    englishNames: ["Heartleaf Philodendron"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "dieffenbachia",
    latinName: "Dieffenbachia",
    turkishNames: ["Difenbahya"],
    englishNames: ["Dumb Cane"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "begonia-rex",
    latinName: "Begonia rex",
    turkishNames: ["Begonya"],
    englishNames: ["Rex Begonia"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 300,
  },
  {
    id: "kalanchoe-blossfeldiana",
    latinName: "Kalanchoe blossfeldiana",
    turkishNames: ["Kalanşo"],
    englishNames: ["Kalanchoe", "Flaming Katy"],
    defaultWateringDays: 10,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "echeveria",
    latinName: "Echeveria",
    turkishNames: ["Taş Gülü"],
    englishNames: ["Echeveria"],
    defaultWateringDays: 14,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 420,
  },
  {
    id: "cactaceae",
    latinName: "Cactaceae",
    turkishNames: ["Kaktüs"],
    englishNames: ["Cactus"],
    defaultWateringDays: 21,
    defaultFeedingDays: 60,
    defaultSoilChangeDays: 540,
  },
  {
    id: "schlumbergera",
    latinName: "Schlumbergera",
    turkishNames: ["Yılbaşı Kaktüsü"],
    englishNames: ["Christmas Cactus"],
    defaultWateringDays: 10,
    defaultFeedingDays: 40,
    defaultSoilChangeDays: 420,
  },
  {
    id: "nephrolepis-exaltata",
    latinName: "Nephrolepis exaltata",
    turkishNames: ["Aşk Merdiveni", "Kılıç Eğreltisi"],
    englishNames: ["Boston Fern"],
    defaultWateringDays: 4,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "peperomia",
    latinName: "Peperomia",
    turkishNames: ["Peperomya"],
    englishNames: ["Peperomia"],
    defaultWateringDays: 9,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 365,
  },
  {
    id: "tradescantia",
    latinName: "Tradescantia",
    turkishNames: ["Telgraf Çiçeği"],
    englishNames: ["Wandering Jew", "Inch Plant"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "cyclamen",
    latinName: "Cyclamen persicum",
    turkishNames: ["Siklamen", "Buhur Çiçeği"],
    englishNames: ["Cyclamen"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 365,
  },
  {
    id: "azalea",
    latinName: "Rhododendron simsii",
    turkishNames: ["Açelya"],
    englishNames: ["Azalea"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 365,
  },
  {
    id: "chamaedorea-elegans",
    latinName: "Chamaedorea elegans",
    turkishNames: ["Dağ Palmiyesi"],
    englishNames: ["Parlor Palm"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "dypsis-lutescens",
    latinName: "Dypsis lutescens",
    turkishNames: ["Areka Palmiyesi"],
    englishNames: ["Areca Palm", "Butterfly Palm"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "strelitzia",
    latinName: "Strelitzia reginae",
    turkishNames: ["Cennet Kuşu"],
    englishNames: ["Bird of Paradise"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "pilea-peperomioides",
    latinName: "Pilea peperomioides",
    turkishNames: ["Çin Para Bitkisi"],
    englishNames: ["Chinese Money Plant", "Pancake Plant"],
    defaultWateringDays: 7,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "hoya-carnosa",
    latinName: "Hoya carnosa",
    turkishNames: ["Mum Çiçeği"],
    englishNames: ["Wax Plant", "Hoya"],
    defaultWateringDays: 10,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 420,
  },
  {
    id: "gardenia",
    latinName: "Gardenia jasminoides",
    turkishNames: ["Gardenya"],
    englishNames: ["Gardenia"],
    defaultWateringDays: 5,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 365,
  },
  {
    id: "codiaeum-variegatum",
    latinName: "Codiaeum variegatum",
    turkishNames: ["Kroton"],
    englishNames: ["Croton"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "aglaonema",
    latinName: "Aglaonema",
    turkishNames: ["Aglonema"],
    englishNames: ["Chinese Evergreen"],
    defaultWateringDays: 8,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "schefflera-arboricola",
    latinName: "Schefflera arboricola",
    turkishNames: ["Şeflera", "Şemsiye Bitkisi"],
    englishNames: ["Schefflera", "Umbrella Plant", "Dwarf Schefflera"],
    defaultWateringDays: 8,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "syngonium-podophyllum",
    latinName: "Syngonium podophyllum",
    turkishNames: ["Ok Ucu Bitkisi", "Singonyum"],
    englishNames: ["Arrowhead Plant", "Goosefoot Plant"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "fittonia-albivenis",
    latinName: "Fittonia albivenis",
    turkishNames: ["Sinir Otu", "Fitonya"],
    englishNames: ["Nerve Plant", "Mosaic Plant"],
    defaultWateringDays: 4,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "beaucarnea-recurvata",
    latinName: "Beaucarnea recurvata",
    turkishNames: ["Fil Ayağı", "At Kuyruğu Palmiyesi"],
    englishNames: ["Ponytail Palm", "Elephant's Foot"],
    defaultWateringDays: 18,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 540,
  },
  {
    id: "asplenium-nidus",
    latinName: "Asplenium nidus",
    turkishNames: ["Kuş Yuvası Eğreltisi"],
    englishNames: ["Bird's Nest Fern"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "adiantum",
    latinName: "Adiantum",
    turkishNames: ["Baldırıkara", "Venüs Saçı"],
    englishNames: ["Maidenhair Fern"],
    defaultWateringDays: 3,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 300,
  },
  {
    id: "senecio-rowleyanus",
    latinName: "Senecio rowleyanus",
    turkishNames: ["İnci Dizisi"],
    englishNames: ["String of Pearls"],
    defaultWateringDays: 14,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 420,
  },
  {
    id: "haworthia",
    latinName: "Haworthia",
    turkishNames: ["Zebra Sukulenti", "Haworthia"],
    englishNames: ["Haworthia", "Zebra Plant"],
    defaultWateringDays: 16,
    defaultFeedingDays: 50,
    defaultSoilChangeDays: 420,
  },
  {
    id: "dracaena-fragrans",
    latinName: "Dracaena fragrans",
    turkishNames: ["Mısır Bitkisi"],
    englishNames: ["Corn Plant", "Cornstalk Dracaena"],
    defaultWateringDays: 9,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 365,
  },
  {
    id: "aspidistra-elatior",
    latinName: "Aspidistra elatior",
    turkishNames: ["Demir Bitkisi"],
    englishNames: ["Cast Iron Plant"],
    defaultWateringDays: 12,
    defaultFeedingDays: 45,
    defaultSoilChangeDays: 420,
  },
  {
    id: "pachira-aquatica",
    latinName: "Pachira aquatica",
    turkishNames: ["Pachira", "Guyana Kestanesi"],
    englishNames: ["Money Tree", "Guiana Chestnut"],
    defaultWateringDays: 9,
    defaultFeedingDays: 35,
    defaultSoilChangeDays: 365,
  },
  {
    id: "pelargonium",
    latinName: "Pelargonium",
    turkishNames: ["Sardunya"],
    englishNames: ["Geranium", "Pelargonium"],
    defaultWateringDays: 6,
    defaultFeedingDays: 25,
    defaultSoilChangeDays: 365,
  },
  {
    id: "euphorbia-pulcherrima",
    latinName: "Euphorbia pulcherrima",
    turkishNames: ["Atatürk Çiçeği", "Yıldız Çiçeği"],
    englishNames: ["Poinsettia"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "hibiscus-rosa-sinensis",
    latinName: "Hibiscus rosa-sinensis",
    turkishNames: ["Japon Gülü", "Çin Gülü"],
    englishNames: ["Hibiscus", "Rose of China"],
    defaultWateringDays: 5,
    defaultFeedingDays: 21,
    defaultSoilChangeDays: 365,
  },
  {
    id: "fatsia-japonica",
    latinName: "Fatsia japonica",
    turkishNames: ["Fatsya"],
    englishNames: ["Japanese Aralia", "Fatsia"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  {
    id: "cordyline-fruticosa",
    latinName: "Cordyline fruticosa",
    turkishNames: ["Kordilin"],
    englishNames: ["Ti Plant", "Cordyline"],
    defaultWateringDays: 6,
    defaultFeedingDays: 30,
    defaultSoilChangeDays: 365,
  },
  // TODO(prod): Remove notification test plant type before production (and delete user plants with this id in plants.json).
  {
    id: "test-notification-plant",
    latinName: "Testus notificatus",
    turkishNames: ["Bildirim Test Bitkisi"],
    englishNames: ["Notification Test Plant"],
    defaultWateringDays: 1,
    defaultFeedingDays: 365,
    defaultSoilChangeDays: 365,
  },
];
